-- Looking at imported data

SELECT *
FROM COVIDDEATHS;

SELECT LOCATION,DATE,TOTAL_CASES,NEW_CASES
FROM COVIDDEATHS
ORDER BY 1,2;

-- Total Cases vs Total Deaths

SELECT LOCATION,TOTAL_CASES,TOTAL_DEATHS,(TOTAL_DEATHS/TOTAL_CASES)*100 AS DEATH_PERCENT
FROM COVIDDEATHS
WHERE LOCATION = 'Antigua and Barbuda' AND TOTAL_CASES <> '';

-- Total Cases vs Population -> Percentage of infected population

SELECT LOCATION,TOTAL_CASES,POPULATION,(TOTAL_CASES/POPULATION)*100 AS INFECTED_POPULATION
FROM COVIDDEATHS
WHERE LOCATION = 'Antigua and Barbuda' AND TOTAL_CASES <> '';

-- Highest Infection Count compared to Population

SELECT LOCATION,POPULATION,MAX(TOTAL_CASES) AS HIGHESTINFECTIONCOUNT,MAX(TOTAL_CASES/POPULATION)*100 AS INFECTED_POPULATION
FROM COVIDDEATHS
GROUP BY LOCATION,POPULATION
ORDER BY HIGHESTINFECTIONCOUNT DESC;		

-- Countries with highest death count per population

SELECT LOCATION,MAX(TOTAL_DEATHS),(MAX(TOTAL_DEATHS)/POPULATION)*100 AS DEATHSBYPOPULATION
FROM COVIDDEATHS
GROUP BY LOCATION
ORDER BY DEATHSBYPOPULATION DESC;

-- Continent wise analysis

SELECT CONTINENT,MAX(TOTAL_DEATHS) AS DEATHCOUNT,POPULATION,(MAX(TOTAL_DEATHS)/POPULATION)*100 AS DEATHSBYPOPULATION
FROM COVIDDEATHS
WHERE CONTINENT <> ''
GROUP BY CONTINENT;

-- Stats across the world date-wise

SELECT DATE,SUM(NEW_CASES) AS CASES, SUM(NEW_DEATHS) AS DEATHS, (SUM(NEW_DEATHS)/SUM(NEW_CASES))*100 AS DEATHPERCENT
FROM COVIDDEATHS
GROUP BY DATE;

-- Total Cases,deaths,death percent

SELECT SUM(NEW_CASES) AS CASES, SUM(NEW_DEATHS) AS DEATHS, (SUM(NEW_DEATHS)/SUM(NEW_CASES))*100 AS DEATHPERCENT
FROM COVIDDEATHS;

-- Vaccination Table

SELECT *
FROM COVIDVACCINATIONS;

-- Joining both the tables

SELECT *
FROM COVIDDEATHS D 
JOIN COVIDVACCINATIONS V
ON D.LOCATION = V.LOCATION;

-- Vaccinated Population

SELECT D.CONTINENT,D.LOCATION,D.DATE,D.POPULATION,V.NEW_VACCINATIONS
FROM COVIDDEATHS D
JOIN COVIDVACCINATIONS V
ON D.LOCATION = V.LOCATION AND D.DATE = V.DATE;

-- Partitioning by Location

SELECT D.CONTINENT,D.LOCATION,D.DATE,D.POPULATION,V.NEW_VACCINATIONS,
SUM(NEW_VACCINATIONS) OVER (PARTITION BY D.LOCATION ORDER BY D.LOCATION,D.DATE) AS ROLLINGCOUNT
FROM COVIDDEATHS D
JOIN COVIDVACCINATIONS V
ON D.LOCATION = V.LOCATION AND D.DATE = V.DATE;

-- Total population vs vaccination

WITH POPVAC
(CONTINENT,LOCATION,DATER,POPULATION,NEW_VACCINATIONS,ROLLINGCOUNT)
AS
(
SELECT D.CONTINENT,D.LOCATION,D.DATE,D.POPULATION,V.NEW_VACCINATIONS,
SUM(NEW_VACCINATIONS) OVER (PARTITION BY D.LOCATION ORDER BY D.LOCATION,D.DATE) AS ROLLINGCOUNT
FROM COVIDDEATHS D
JOIN COVIDVACCINATIONS V
ON D.LOCATION = V.LOCATION AND D.DATE = V.DATE
WHERE D.CONTINENT IS NOT NULL
)

SELECT *
FROM POPVAC;

-- Creating View

CREATE VIEW PERCENTPOPULATIONVACC
AS
SELECT D.CONTINENT,D.LOCATION,D.DATE,D.POPULATION,V.NEW_VACCINATIONS,
SUM(NEW_VACCINATIONS) OVER (PARTITION BY D.LOCATION ORDER BY D.LOCATION,D.DATE) AS ROLLINGCOUNT
FROM COVIDDEATHS D
JOIN COVIDVACCINATIONS V
ON D.LOCATION = V.LOCATION AND D.DATE = V.DATE
WHERE D.CONTINENT IS NOT NULL;


 
